OPENAI_API_KEY="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"
RUNPOD_API_TOKEN="5U9J2HTS080JT8G1IQ0PG1Z7RWHKYNZXXBUHCITI"
AWS_ACCESS_KEY_ID="AKIAWNZZWBKFQ4IYQFUG"
AWS_ACCESS_KEY_SECRET="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"